#!/bin/sh

#  gilbert.nvim use this package
#  cannot use glide, so it use for now
go get -u github.com/neovim/go-client/...
go get -u github.com/NoahOrberg/gilbert.nvim/...
go get -u github.com/NoahOrberg/gilbert/...
go get -u github.com/NoahOrberg/nvim-go-util/...
